### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by bomberstudios** [fhuel/Unsplash-It-Sketch#17]
Hi there,

As you probably know, `setPatternImage:` has been deprecated for a while, and it will be removed in Sketch v40. Please update your Plugin to use `setImage:` instead or it won't work in the next release :)

**Comment by fhuel** [comment]
Thank you so much for letting me know Ale,

really really appreciate that!

**Comment by romiem** [comment]
When will this plugin be updated? I use Unsplash It almost daily! (v40.0 of Sketch is already out and this plugin is now broken)

**Comment by BrianSipple** [comment]
I can confirm alongside @romiem that this plugin is now broken in Sketch v40. @bomberstudios, for those browsing the list of issues, it might be helpful to rename this one to reflect that.

**Comment by alexdoronin** [comment]
To fix it:  
~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Unsplash It Sketch/Unsplash It.sketchplugin/Contents/Sketch/unsplashit.cocoascript 

Instead of: 
`fill.setImage( imageData );`

This line:
`fill.setImage(MSImageData.alloc().initWithImage_convertColorSpace(imageData, false))`

It works in v40.

**Comment by fhuel** [comment]
hey everyone, finally working fine now. 
Sorry guys if it took me this long :P
