### ISSUE TITLE
Request: Add Placehold.it!

### ISSUE THREAD

**Issue by luxlogica** [fhuel/Unsplash-It-Sketch#4]
I love this plugin, but in some instances it would actually be easier to simply have a generic placeholder, such as the ones provided by the excellent "Placehold.it" website. Like Unsplash.it, they provide a free, URL-based api with some optionally configurable parameters (text to be displayed, colour of text and background, picture file format). 

Based on the way the plugin works currently with the Unsplash.it images, I'd see you adding 2 menu items: a standard "Placehold.it", and a "Placehold.it+Options"...

**Comment by fhuel** [comment]
Hey, thanks.
I get what you mean... However this particular plugin exists to have really fast and convenient way to use great photography as placeholder images, instead of grey boxes with a cross or measures inside. This kind of things are already quite fast and easy to create with just Sketch.

I agree that there are particular times when you need these grey boxes with measures inside, and this is a really good idea for another plugin indeed.  We can work together on that if you like.
