### ISSUE TITLE
constant crashing

### ISSUE THREAD

**Issue by nikiniki9doors** [fhuel/Unsplash-It-Sketch#5]
Cannot get this plugin to work - every time it crashes sketch.

**Comment by fhuel** [comment]
Hey, thank you for letting me know.
Could you please let me know the version of both Sketch and OsX ?

**Comment by MarttiR** [comment]
The plugin was working excellently for some time (Sketch 3.4.4-17249 & El Capitan), but suddenly started to crash Sketch on every activation. The problem seems to happen on line 47:

`var imageData = NSImage.alloc().initWithData( get(imageURL) );`

There doesn't seem to be any logic validating whether the HTTP response is OK before it's passed to `initWithData()`. I'm not in any way familiar with the environment, but perhaps the API doesn't like too many requests and is returning an error?

**Comment by fhuel** [comment]
Thank you @MarttiR , I think you hit the point
Working on that
Thanks!

**Comment by ckuchibh** [comment]
When is the fix expected?

**Comment by howardstein** [comment]
Installed it on Sketch 40. Made a series of rectangles — (I'm a beginner w/Sketch), ran the plugin and it turned one grey rectangle white. Whether selecting one shape or several, am not getting any images loading into the selected shape. Suggestions? Thanks.

**Comment by fhuel** [comment]
there was an in incompatibility bug with Sketch 4. Solved now, the plugin should run smoothly now

**Comment by ckuchibh** [comment]
Thank you!  

Best,
Chandra Kuchibhotla

DISCLAIMER: The information contained in this message (including attached documents) may be privileged, confidential, and protected from disclosure. If you are not the intended recipient, or an employee, or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately by replying to the message and deleting from your computer. Opinions, conclusions, and other information in this message that do not relate to official CKLABS business are those of the sender and are neither given nor endorsed by CKLABS.

**Comment by sureshmurali** [comment]
Sketch 43.1
OS X 10.12.4
Crashes sketch application :(
